//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf_Nhr_unit
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", ConfigurationName="Wcf_Nhr_unit.UnitService")]
    public interface UnitService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.izintypelistResponse> izintypelistAsync(Wcf_Nhr_unit.izintypelist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.infobyidResponse> infobyidAsync(Wcf_Nhr_unit.infobyid request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.unvanlistResponse> unvanlistAsync(Wcf_Nhr_unit.unvanlist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.birimagacibytypeResponse> birimagacibytypeAsync(Wcf_Nhr_unit.birimagacibytype request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.masterbirimlistResponse> masterbirimlistAsync(Wcf_Nhr_unit.masterbirimlist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.fiiligorevyerleribytypeResponse> fiiligorevyerleribytypeAsync(Wcf_Nhr_unit.fiiligorevyerleribytype request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.saglikizintypelistResponse> saglikizintypelistAsync(Wcf_Nhr_unit.saglikizintypelist request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/")]
    public partial class wsmap
    {
        
        private long mapkeyField;
        
        private bool mapkeyFieldSpecified;
        
        private string mapvalueField;
        
        private wsexception wsexceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long mapkey
        {
            get
            {
                return this.mapkeyField;
            }
            set
            {
                this.mapkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mapkeySpecified
        {
            get
            {
                return this.mapkeyFieldSpecified;
            }
            set
            {
                this.mapkeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mapvalue
        {
            get
            {
                return this.mapvalueField;
            }
            set
            {
                this.mapvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public wsexception wsexception
        {
            get
            {
                return this.wsexceptionField;
            }
            set
            {
                this.wsexceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/")]
    public partial class wsexception
    {
        
        private string wsexceptionMessageField;
        
        private string wsexceptionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string wsexceptionMessage
        {
            get
            {
                return this.wsexceptionMessageField;
            }
            set
            {
                this.wsexceptionMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wsexceptionCode
        {
            get
            {
                return this.wsexceptionCodeField;
            }
            set
            {
                this.wsexceptionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/")]
    public partial class wsunvan
    {
        
        private int unvanIdField;
        
        private bool unvanIdFieldSpecified;
        
        private string unvanAdField;
        
        private string unvanKisaltmaField;
        
        private string unvanIngilizceadField;
        
        private long unvanKoduField;
        
        private bool unvanKoduFieldSpecified;
        
        private int unvanZorunluderssaatField;
        
        private bool unvanZorunluderssaatFieldSpecified;
        
        private string unvanTipiField;
        
        private wsexception wsexceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int unvanId
        {
            get
            {
                return this.unvanIdField;
            }
            set
            {
                this.unvanIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unvanIdSpecified
        {
            get
            {
                return this.unvanIdFieldSpecified;
            }
            set
            {
                this.unvanIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string unvanAd
        {
            get
            {
                return this.unvanAdField;
            }
            set
            {
                this.unvanAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string unvanKisaltma
        {
            get
            {
                return this.unvanKisaltmaField;
            }
            set
            {
                this.unvanKisaltmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string unvanIngilizcead
        {
            get
            {
                return this.unvanIngilizceadField;
            }
            set
            {
                this.unvanIngilizceadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long unvanKodu
        {
            get
            {
                return this.unvanKoduField;
            }
            set
            {
                this.unvanKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unvanKoduSpecified
        {
            get
            {
                return this.unvanKoduFieldSpecified;
            }
            set
            {
                this.unvanKoduFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int unvanZorunluderssaat
        {
            get
            {
                return this.unvanZorunluderssaatField;
            }
            set
            {
                this.unvanZorunluderssaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unvanZorunluderssaatSpecified
        {
            get
            {
                return this.unvanZorunluderssaatFieldSpecified;
            }
            set
            {
                this.unvanZorunluderssaatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string unvanTipi
        {
            get
            {
                return this.unvanTipiField;
            }
            set
            {
                this.unvanTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public wsexception wsexception
        {
            get
            {
                return this.wsexceptionField;
            }
            set
            {
                this.wsexceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/")]
    public partial class wsidarigorev
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string idarigorevAdField;
        
        private string idarigorevSoyadField;
        
        private long idarigorevTckimliknoField;
        
        private bool idarigorevTckimliknoFieldSpecified;
        
        private System.DateTime idarigorevBastarField;
        
        private bool idarigorevBastarFieldSpecified;
        
        private System.DateTime idarigorevBittarField;
        
        private bool idarigorevBittarFieldSpecified;
        
        private string idarigorevAciklamaField;
        
        private bool idarigorevIsvekaletenField;
        
        private bool idarigorevIsvekaletenFieldSpecified;
        
        private System.DateTime dateCreatedField;
        
        private bool dateCreatedFieldSpecified;
        
        private System.DateTime lastUpdatedField;
        
        private bool lastUpdatedFieldSpecified;
        
        private double unvanEkdersoraniField;
        
        private bool unvanEkdersoraniFieldSpecified;
        
        private string idarigorevUnvanseviyeField;
        
        private string idarigorevUnvanField;
        
        private int idarigorevunvanidField;
        
        private bool idarigorevunvanidFieldSpecified;
        
        private string idarigorevBirimField;
        
        private string idarigorevMasterbirimField;
        
        private int idarigorevMasterbirimidField;
        
        private bool idarigorevMasterbirimidFieldSpecified;
        
        private string idarigorunvanZorunluderssaatField;
        
        private int idarigorevBirimidField;
        
        private bool idarigorevBirimidFieldSpecified;
        
        private string idarigorevBolumField;
        
        private int idarigorevBolumidField;
        
        private bool idarigorevBolumidFieldSpecified;
        
        private string idarigorevAbdField;
        
        private int idarigorevAbdidField;
        
        private bool idarigorevAbdidFieldSpecified;
        
        private bool idarigorevIsuhdesindeField;
        
        private bool idarigorevIsuhdesindeFieldSpecified;
        
        private bool idarigorevIstedvirenField;
        
        private bool idarigorevIstedvirenFieldSpecified;
        
        private wsexception wsexceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idarigorevAd
        {
            get
            {
                return this.idarigorevAdField;
            }
            set
            {
                this.idarigorevAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idarigorevSoyad
        {
            get
            {
                return this.idarigorevSoyadField;
            }
            set
            {
                this.idarigorevSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idarigorevTckimlikno
        {
            get
            {
                return this.idarigorevTckimliknoField;
            }
            set
            {
                this.idarigorevTckimliknoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevTckimliknoSpecified
        {
            get
            {
                return this.idarigorevTckimliknoFieldSpecified;
            }
            set
            {
                this.idarigorevTckimliknoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime idarigorevBastar
        {
            get
            {
                return this.idarigorevBastarField;
            }
            set
            {
                this.idarigorevBastarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevBastarSpecified
        {
            get
            {
                return this.idarigorevBastarFieldSpecified;
            }
            set
            {
                this.idarigorevBastarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime idarigorevBittar
        {
            get
            {
                return this.idarigorevBittarField;
            }
            set
            {
                this.idarigorevBittarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevBittarSpecified
        {
            get
            {
                return this.idarigorevBittarFieldSpecified;
            }
            set
            {
                this.idarigorevBittarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string idarigorevAciklama
        {
            get
            {
                return this.idarigorevAciklamaField;
            }
            set
            {
                this.idarigorevAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool idarigorevIsvekaleten
        {
            get
            {
                return this.idarigorevIsvekaletenField;
            }
            set
            {
                this.idarigorevIsvekaletenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevIsvekaletenSpecified
        {
            get
            {
                return this.idarigorevIsvekaletenFieldSpecified;
            }
            set
            {
                this.idarigorevIsvekaletenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime dateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreatedSpecified
        {
            get
            {
                return this.dateCreatedFieldSpecified;
            }
            set
            {
                this.dateCreatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime lastUpdated
        {
            get
            {
                return this.lastUpdatedField;
            }
            set
            {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdatedSpecified
        {
            get
            {
                return this.lastUpdatedFieldSpecified;
            }
            set
            {
                this.lastUpdatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double unvanEkdersorani
        {
            get
            {
                return this.unvanEkdersoraniField;
            }
            set
            {
                this.unvanEkdersoraniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unvanEkdersoraniSpecified
        {
            get
            {
                return this.unvanEkdersoraniFieldSpecified;
            }
            set
            {
                this.unvanEkdersoraniFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string idarigorevUnvanseviye
        {
            get
            {
                return this.idarigorevUnvanseviyeField;
            }
            set
            {
                this.idarigorevUnvanseviyeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string idarigorevUnvan
        {
            get
            {
                return this.idarigorevUnvanField;
            }
            set
            {
                this.idarigorevUnvanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int idarigorevunvanid
        {
            get
            {
                return this.idarigorevunvanidField;
            }
            set
            {
                this.idarigorevunvanidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevunvanidSpecified
        {
            get
            {
                return this.idarigorevunvanidFieldSpecified;
            }
            set
            {
                this.idarigorevunvanidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string idarigorevBirim
        {
            get
            {
                return this.idarigorevBirimField;
            }
            set
            {
                this.idarigorevBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string idarigorevMasterbirim
        {
            get
            {
                return this.idarigorevMasterbirimField;
            }
            set
            {
                this.idarigorevMasterbirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int idarigorevMasterbirimid
        {
            get
            {
                return this.idarigorevMasterbirimidField;
            }
            set
            {
                this.idarigorevMasterbirimidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevMasterbirimidSpecified
        {
            get
            {
                return this.idarigorevMasterbirimidFieldSpecified;
            }
            set
            {
                this.idarigorevMasterbirimidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string idarigorunvanZorunluderssaat
        {
            get
            {
                return this.idarigorunvanZorunluderssaatField;
            }
            set
            {
                this.idarigorunvanZorunluderssaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int idarigorevBirimid
        {
            get
            {
                return this.idarigorevBirimidField;
            }
            set
            {
                this.idarigorevBirimidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevBirimidSpecified
        {
            get
            {
                return this.idarigorevBirimidFieldSpecified;
            }
            set
            {
                this.idarigorevBirimidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string idarigorevBolum
        {
            get
            {
                return this.idarigorevBolumField;
            }
            set
            {
                this.idarigorevBolumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int idarigorevBolumid
        {
            get
            {
                return this.idarigorevBolumidField;
            }
            set
            {
                this.idarigorevBolumidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevBolumidSpecified
        {
            get
            {
                return this.idarigorevBolumidFieldSpecified;
            }
            set
            {
                this.idarigorevBolumidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string idarigorevAbd
        {
            get
            {
                return this.idarigorevAbdField;
            }
            set
            {
                this.idarigorevAbdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int idarigorevAbdid
        {
            get
            {
                return this.idarigorevAbdidField;
            }
            set
            {
                this.idarigorevAbdidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevAbdidSpecified
        {
            get
            {
                return this.idarigorevAbdidFieldSpecified;
            }
            set
            {
                this.idarigorevAbdidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public bool idarigorevIsuhdesinde
        {
            get
            {
                return this.idarigorevIsuhdesindeField;
            }
            set
            {
                this.idarigorevIsuhdesindeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevIsuhdesindeSpecified
        {
            get
            {
                return this.idarigorevIsuhdesindeFieldSpecified;
            }
            set
            {
                this.idarigorevIsuhdesindeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public bool idarigorevIstedviren
        {
            get
            {
                return this.idarigorevIstedvirenField;
            }
            set
            {
                this.idarigorevIstedvirenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idarigorevIstedvirenSpecified
        {
            get
            {
                return this.idarigorevIstedvirenFieldSpecified;
            }
            set
            {
                this.idarigorevIstedvirenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public wsexception wsexception
        {
            get
            {
                return this.wsexceptionField;
            }
            set
            {
                this.wsexceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/")]
    public partial class wsnode
    {
        
        private int nodeIdField;
        
        private bool nodeIdFieldSpecified;
        
        private string nodeAdField;
        
        private string nodeAciklamaField;
        
        private bool nodeIsaktifField;
        
        private bool nodeIsaktifFieldSpecified;
        
        private bool nodeIsmasterbirimField;
        
        private bool nodeIsmasterbirimFieldSpecified;
        
        private int nodeYokkoduField;
        
        private bool nodeYokkoduFieldSpecified;
        
        private string nodeKisaltmaField;
        
        private string nodeTipiField;
        
        private string nodeSehirField;
        
        private string nodeKadrotipiField;
        
        private string nodeSeviyetipiField;
        
        private string nodeBirimtipiField;
        
        private string nodeParentField;
        
        private int nodeParentidField;
        
        private bool nodeParentidFieldSpecified;
        
        private string nodeMasterbirimField;
        
        private int nodeMasterbirimidField;
        
        private bool nodeMasterbirimidFieldSpecified;
        
        private string nodeBirimtipi2adiField;
        
        private wsidarigorev[] wsidarigorevListField;
        
        private wsmap[] ayrilanlarTckimlikListField;
        
        private System.Nullable<long>[] disiplincezasiTckimlikListField;
        
        private wsexception wsexceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int nodeId
        {
            get
            {
                return this.nodeIdField;
            }
            set
            {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeIdSpecified
        {
            get
            {
                return this.nodeIdFieldSpecified;
            }
            set
            {
                this.nodeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nodeAd
        {
            get
            {
                return this.nodeAdField;
            }
            set
            {
                this.nodeAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nodeAciklama
        {
            get
            {
                return this.nodeAciklamaField;
            }
            set
            {
                this.nodeAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool nodeIsaktif
        {
            get
            {
                return this.nodeIsaktifField;
            }
            set
            {
                this.nodeIsaktifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeIsaktifSpecified
        {
            get
            {
                return this.nodeIsaktifFieldSpecified;
            }
            set
            {
                this.nodeIsaktifFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool nodeIsmasterbirim
        {
            get
            {
                return this.nodeIsmasterbirimField;
            }
            set
            {
                this.nodeIsmasterbirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeIsmasterbirimSpecified
        {
            get
            {
                return this.nodeIsmasterbirimFieldSpecified;
            }
            set
            {
                this.nodeIsmasterbirimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nodeYokkodu
        {
            get
            {
                return this.nodeYokkoduField;
            }
            set
            {
                this.nodeYokkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeYokkoduSpecified
        {
            get
            {
                return this.nodeYokkoduFieldSpecified;
            }
            set
            {
                this.nodeYokkoduFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nodeKisaltma
        {
            get
            {
                return this.nodeKisaltmaField;
            }
            set
            {
                this.nodeKisaltmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nodeTipi
        {
            get
            {
                return this.nodeTipiField;
            }
            set
            {
                this.nodeTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nodeSehir
        {
            get
            {
                return this.nodeSehirField;
            }
            set
            {
                this.nodeSehirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nodeKadrotipi
        {
            get
            {
                return this.nodeKadrotipiField;
            }
            set
            {
                this.nodeKadrotipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nodeSeviyetipi
        {
            get
            {
                return this.nodeSeviyetipiField;
            }
            set
            {
                this.nodeSeviyetipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nodeBirimtipi
        {
            get
            {
                return this.nodeBirimtipiField;
            }
            set
            {
                this.nodeBirimtipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string nodeParent
        {
            get
            {
                return this.nodeParentField;
            }
            set
            {
                this.nodeParentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int nodeParentid
        {
            get
            {
                return this.nodeParentidField;
            }
            set
            {
                this.nodeParentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeParentidSpecified
        {
            get
            {
                return this.nodeParentidFieldSpecified;
            }
            set
            {
                this.nodeParentidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string nodeMasterbirim
        {
            get
            {
                return this.nodeMasterbirimField;
            }
            set
            {
                this.nodeMasterbirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int nodeMasterbirimid
        {
            get
            {
                return this.nodeMasterbirimidField;
            }
            set
            {
                this.nodeMasterbirimidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeMasterbirimidSpecified
        {
            get
            {
                return this.nodeMasterbirimidFieldSpecified;
            }
            set
            {
                this.nodeMasterbirimidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string nodeBirimtipi2adi
        {
            get
            {
                return this.nodeBirimtipi2adiField;
            }
            set
            {
                this.nodeBirimtipi2adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wsidarigorevList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public wsidarigorev[] wsidarigorevList
        {
            get
            {
                return this.wsidarigorevListField;
            }
            set
            {
                this.wsidarigorevListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ayrilanlarTckimlikList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public wsmap[] ayrilanlarTckimlikList
        {
            get
            {
                return this.ayrilanlarTckimlikListField;
            }
            set
            {
                this.ayrilanlarTckimlikListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("disiplincezasiTckimlikList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public System.Nullable<long>[] disiplincezasiTckimlikList
        {
            get
            {
                return this.disiplincezasiTckimlikListField;
            }
            set
            {
                this.disiplincezasiTckimlikListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public wsexception wsexception
        {
            get
            {
                return this.wsexceptionField;
            }
            set
            {
                this.wsexceptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="izintypelist", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class izintypelist
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        public izintypelist()
        {
        }
        
        public izintypelist(string wsusername, string wspassword)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="izintypelistResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class izintypelistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsmap[] @return;
        
        public izintypelistResponse()
        {
        }
        
        public izintypelistResponse(Wcf_Nhr_unit.wsmap[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="infobyid", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class infobyid
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nodeId;
        
        public infobyid()
        {
        }
        
        public infobyid(string wsusername, string wspassword, int nodeId)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
            this.nodeId = nodeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="infobyidResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class infobyidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsnode @return;
        
        public infobyidResponse()
        {
        }
        
        public infobyidResponse(Wcf_Nhr_unit.wsnode @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unvanlist", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class unvanlist
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        public unvanlist()
        {
        }
        
        public unvanlist(string wsusername, string wspassword)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unvanlistResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class unvanlistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsunvan[] @return;
        
        public unvanlistResponse()
        {
        }
        
        public unvanlistResponse(Wcf_Nhr_unit.wsunvan[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="birimagacibytype", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class birimagacibytype
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int typeId;
        
        public birimagacibytype()
        {
        }
        
        public birimagacibytype(string wsusername, string wspassword, int typeId)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
            this.typeId = typeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="birimagacibytypeResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class birimagacibytypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsnode[] @return;
        
        public birimagacibytypeResponse()
        {
        }
        
        public birimagacibytypeResponse(Wcf_Nhr_unit.wsnode[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="masterbirimlist", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class masterbirimlist
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        public masterbirimlist()
        {
        }
        
        public masterbirimlist(string wsusername, string wspassword)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="masterbirimlistResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class masterbirimlistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsnode[] @return;
        
        public masterbirimlistResponse()
        {
        }
        
        public masterbirimlistResponse(Wcf_Nhr_unit.wsnode[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fiiligorevyerleribytype", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class fiiligorevyerleribytype
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int typeId;
        
        public fiiligorevyerleribytype()
        {
        }
        
        public fiiligorevyerleribytype(string wsusername, string wspassword, int typeId)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
            this.typeId = typeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fiiligorevyerleribytypeResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class fiiligorevyerleribytypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsnode[] @return;
        
        public fiiligorevyerleribytypeResponse()
        {
        }
        
        public fiiligorevyerleribytypeResponse(Wcf_Nhr_unit.wsnode[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saglikizintypelist", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class saglikizintypelist
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wspassword;
        
        public saglikizintypelist()
        {
        }
        
        public saglikizintypelist(string wsusername, string wspassword)
        {
            this.wsusername = wsusername;
            this.wspassword = wspassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saglikizintypelistResponse", WrapperNamespace="http://webservices.nhrweb.netiket.com.tr/", IsWrapped=true)]
    public partial class saglikizintypelistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.nhrweb.netiket.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wcf_Nhr_unit.wsmap[] @return;
        
        public saglikizintypelistResponse()
        {
        }
        
        public saglikizintypelistResponse(Wcf_Nhr_unit.wsmap[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface UnitServiceChannel : Wcf_Nhr_unit.UnitService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UnitServiceClient : System.ServiceModel.ClientBase<Wcf_Nhr_unit.UnitService>, Wcf_Nhr_unit.UnitService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UnitServiceClient() : 
                base(UnitServiceClient.GetDefaultBinding(), UnitServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UnitServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UnitServiceClient.GetBindingForEndpoint(endpointConfiguration), UnitServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UnitServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UnitServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.izintypelistResponse> Wcf_Nhr_unit.UnitService.izintypelistAsync(Wcf_Nhr_unit.izintypelist request)
        {
            return base.Channel.izintypelistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.izintypelistResponse> izintypelistAsync(string wsusername, string wspassword)
        {
            Wcf_Nhr_unit.izintypelist inValue = new Wcf_Nhr_unit.izintypelist();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            return ((Wcf_Nhr_unit.UnitService)(this)).izintypelistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.infobyidResponse> Wcf_Nhr_unit.UnitService.infobyidAsync(Wcf_Nhr_unit.infobyid request)
        {
            return base.Channel.infobyidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.infobyidResponse> infobyidAsync(string wsusername, string wspassword, int nodeId)
        {
            Wcf_Nhr_unit.infobyid inValue = new Wcf_Nhr_unit.infobyid();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            inValue.nodeId = nodeId;
            return ((Wcf_Nhr_unit.UnitService)(this)).infobyidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.unvanlistResponse> Wcf_Nhr_unit.UnitService.unvanlistAsync(Wcf_Nhr_unit.unvanlist request)
        {
            return base.Channel.unvanlistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.unvanlistResponse> unvanlistAsync(string wsusername, string wspassword)
        {
            Wcf_Nhr_unit.unvanlist inValue = new Wcf_Nhr_unit.unvanlist();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            return ((Wcf_Nhr_unit.UnitService)(this)).unvanlistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.birimagacibytypeResponse> Wcf_Nhr_unit.UnitService.birimagacibytypeAsync(Wcf_Nhr_unit.birimagacibytype request)
        {
            return base.Channel.birimagacibytypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.birimagacibytypeResponse> birimagacibytypeAsync(string wsusername, string wspassword, int typeId)
        {
            Wcf_Nhr_unit.birimagacibytype inValue = new Wcf_Nhr_unit.birimagacibytype();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            inValue.typeId = typeId;
            return ((Wcf_Nhr_unit.UnitService)(this)).birimagacibytypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.masterbirimlistResponse> Wcf_Nhr_unit.UnitService.masterbirimlistAsync(Wcf_Nhr_unit.masterbirimlist request)
        {
            return base.Channel.masterbirimlistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.masterbirimlistResponse> masterbirimlistAsync(string wsusername, string wspassword)
        {
            Wcf_Nhr_unit.masterbirimlist inValue = new Wcf_Nhr_unit.masterbirimlist();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            return ((Wcf_Nhr_unit.UnitService)(this)).masterbirimlistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.fiiligorevyerleribytypeResponse> Wcf_Nhr_unit.UnitService.fiiligorevyerleribytypeAsync(Wcf_Nhr_unit.fiiligorevyerleribytype request)
        {
            return base.Channel.fiiligorevyerleribytypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.fiiligorevyerleribytypeResponse> fiiligorevyerleribytypeAsync(string wsusername, string wspassword, int typeId)
        {
            Wcf_Nhr_unit.fiiligorevyerleribytype inValue = new Wcf_Nhr_unit.fiiligorevyerleribytype();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            inValue.typeId = typeId;
            return ((Wcf_Nhr_unit.UnitService)(this)).fiiligorevyerleribytypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Nhr_unit.saglikizintypelistResponse> Wcf_Nhr_unit.UnitService.saglikizintypelistAsync(Wcf_Nhr_unit.saglikizintypelist request)
        {
            return base.Channel.saglikizintypelistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Nhr_unit.saglikizintypelistResponse> saglikizintypelistAsync(string wsusername, string wspassword)
        {
            Wcf_Nhr_unit.saglikizintypelist inValue = new Wcf_Nhr_unit.saglikizintypelist();
            inValue.wsusername = wsusername;
            inValue.wspassword = wspassword;
            return ((Wcf_Nhr_unit.UnitService)(this)).saglikizintypelistAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UnitServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UnitServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://nhr.bayburt.edu.tr/webservices/unit");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UnitServiceClient.GetBindingForEndpoint(EndpointConfiguration.UnitServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UnitServiceClient.GetEndpointAddress(EndpointConfiguration.UnitServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            UnitServicePort,
        }
    }
}
