//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf_Ogr_ogrservice
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IslemSonuc", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrContact_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrContactUnipaMasterDB_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrAddress_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrCiftYandal_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrMktr_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrOgretimYiliDonemi_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrOgretimYiliDonemiDetay_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrInformationOgrNo_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrInformation_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.UyrukInformation_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.SehirIlceInformation_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.ValidateOgrNo_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.ValidateTckn_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrImage_Response))]
    public partial class IslemSonuc : object
    {
        
        private string AciklamaField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrContact_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrContact_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrContact[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrContact[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrContactUnipaMasterDB_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrContactUnipaMasterDB_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrContactUnipaMasterDB DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrContactUnipaMasterDB Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrAddress_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrAddress_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrAddress[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrAddress[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrCiftYandal_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrCiftYandal_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrCiftYandal DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrCiftYandal Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrMktr_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrMktr_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrMktr[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrMktr[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrOgretimYiliDonemi_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrOgretimYiliDonemi_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrOgretimYiliDonemi[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrOgretimYiliDonemi[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrOgretimYiliDonemiDetay_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrOgretimYiliDonemiDetay_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrOgretimYiliDonemiDetay[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrOgretimYiliDonemiDetay[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrInformationOgrNo_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrInformationOgrNo_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrInformation DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrInformation Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrInformation_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrInformation_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrInformation[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrInformation[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyrukInformation_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class UyrukInformation_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.UyrukInformation[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.UyrukInformation[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SehirIlceInformation_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class SehirIlceInformation_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.SehirIlceInformation[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.SehirIlceInformation[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateOgrNo_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class ValidateOgrNo_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.Validate DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.Validate Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTckn_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class ValidateTckn_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.Validate[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.Validate[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrImage_Response", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrImage_Response : Wcf_Ogr_ogrservice.IslemSonuc
    {
        
        private Wcf_Ogr_ogrservice.OgrImage DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wcf_Ogr_ogrservice.OgrImage Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrImage", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrImage : object
    {
        
        private int OgrenciFotoIDField;
        
        private byte[] ResimField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciFotoID
        {
            get
            {
                return this.OgrenciFotoIDField;
            }
            set
            {
                this.OgrenciFotoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Resim
        {
            get
            {
                return this.ResimField;
            }
            set
            {
                this.ResimField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrContact", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrContact : object
    {
        
        private int IletisimIDField;
        
        private string IletisimTuruField;
        
        private int IletisimTuru_IDField;
        
        private string InfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IletisimID
        {
            get
            {
                return this.IletisimIDField;
            }
            set
            {
                this.IletisimIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IletisimTuru
        {
            get
            {
                return this.IletisimTuruField;
            }
            set
            {
                this.IletisimTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IletisimTuru_ID
        {
            get
            {
                return this.IletisimTuru_IDField;
            }
            set
            {
                this.IletisimTuru_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrContactUnipaMasterDB", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrContactUnipaMasterDB : object
    {
        
        private string GsmField;
        
        private string KulidField;
        
        private string TelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gsm
        {
            get
            {
                return this.GsmField;
            }
            set
            {
                this.GsmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kulid
        {
            get
            {
                return this.KulidField;
            }
            set
            {
                this.KulidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this.TelField;
            }
            set
            {
                this.TelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrAddress", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrAddress : object
    {
        
        private string AdresField;
        
        private int AdresIDField;
        
        private string AdresTuruField;
        
        private int AdresTuru_IDField;
        
        private string IlField;
        
        private System.Nullable<int> Il_IDField;
        
        private string IlceField;
        
        private System.Nullable<int> Ilce_IDField;
        
        private string UyrukField;
        
        private System.Nullable<int> Uyruk_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdresID
        {
            get
            {
                return this.AdresIDField;
            }
            set
            {
                this.AdresIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdresTuru
        {
            get
            {
                return this.AdresTuruField;
            }
            set
            {
                this.AdresTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdresTuru_ID
        {
            get
            {
                return this.AdresTuru_IDField;
            }
            set
            {
                this.AdresTuru_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il
        {
            get
            {
                return this.IlField;
            }
            set
            {
                this.IlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Il_ID
        {
            get
            {
                return this.Il_IDField;
            }
            set
            {
                this.Il_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce
        {
            get
            {
                return this.IlceField;
            }
            set
            {
                this.IlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ilce_ID
        {
            get
            {
                return this.Ilce_IDField;
            }
            set
            {
                this.Ilce_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Uyruk_ID
        {
            get
            {
                return this.Uyruk_IDField;
            }
            set
            {
                this.Uyruk_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrCiftYandal", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrCiftYandal : object
    {
        
        private string CiftYanDalDurumField;
        
        private System.Nullable<int> CiftYanDalDurum_IDField;
        
        private System.Nullable<System.DateTime> CiftYanDalKayitTarihiField;
        
        private System.Nullable<int> CiftYanDalKayitYiliField;
        
        private System.Nullable<System.DateTime> CiftYanDalMezuniyetTarihiField;
        
        private string CiftYanDalOrganizasyonField;
        
        private string CiftYanDalOrganizasyonProgramField;
        
        private System.Nullable<int> CiftYanDalOrganizasyonProgram_IDField;
        
        private System.Nullable<int> CiftYanDalOrganizasyon_IDField;
        
        private string CiftYandalField;
        
        private int CiftYandal_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiftYanDalDurum
        {
            get
            {
                return this.CiftYanDalDurumField;
            }
            set
            {
                this.CiftYanDalDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiftYanDalDurum_ID
        {
            get
            {
                return this.CiftYanDalDurum_IDField;
            }
            set
            {
                this.CiftYanDalDurum_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CiftYanDalKayitTarihi
        {
            get
            {
                return this.CiftYanDalKayitTarihiField;
            }
            set
            {
                this.CiftYanDalKayitTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiftYanDalKayitYili
        {
            get
            {
                return this.CiftYanDalKayitYiliField;
            }
            set
            {
                this.CiftYanDalKayitYiliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CiftYanDalMezuniyetTarihi
        {
            get
            {
                return this.CiftYanDalMezuniyetTarihiField;
            }
            set
            {
                this.CiftYanDalMezuniyetTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiftYanDalOrganizasyon
        {
            get
            {
                return this.CiftYanDalOrganizasyonField;
            }
            set
            {
                this.CiftYanDalOrganizasyonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiftYanDalOrganizasyonProgram
        {
            get
            {
                return this.CiftYanDalOrganizasyonProgramField;
            }
            set
            {
                this.CiftYanDalOrganizasyonProgramField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiftYanDalOrganizasyonProgram_ID
        {
            get
            {
                return this.CiftYanDalOrganizasyonProgram_IDField;
            }
            set
            {
                this.CiftYanDalOrganizasyonProgram_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiftYanDalOrganizasyon_ID
        {
            get
            {
                return this.CiftYanDalOrganizasyon_IDField;
            }
            set
            {
                this.CiftYanDalOrganizasyon_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiftYandal
        {
            get
            {
                return this.CiftYandalField;
            }
            set
            {
                this.CiftYandalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiftYandal_ID
        {
            get
            {
                return this.CiftYandal_IDField;
            }
            set
            {
                this.CiftYandal_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrMktr", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrMktr : object
    {
        
        private int CinsiyetField;
        
        private bool IsYerliField;
        
        private int MktrField;
        
        private int OgretimTuruField;
        
        private int Program_IDField;
        
        private System.Nullable<int> YoksisBirim_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsYerli
        {
            get
            {
                return this.IsYerliField;
            }
            set
            {
                this.IsYerliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mktr
        {
            get
            {
                return this.MktrField;
            }
            set
            {
                this.MktrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgretimTuru
        {
            get
            {
                return this.OgretimTuruField;
            }
            set
            {
                this.OgretimTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Program_ID
        {
            get
            {
                return this.Program_IDField;
            }
            set
            {
                this.Program_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YoksisBirim_ID
        {
            get
            {
                return this.YoksisBirim_IDField;
            }
            set
            {
                this.YoksisBirim_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrOgretimYiliDonemi", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrOgretimYiliDonemi : object
    {
        
        private string OgretimDonemiField;
        
        private int OgretimDonemi_IDField;
        
        private int OgretimYiliField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgretimDonemi
        {
            get
            {
                return this.OgretimDonemiField;
            }
            set
            {
                this.OgretimDonemiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgretimDonemi_ID
        {
            get
            {
                return this.OgretimDonemi_IDField;
            }
            set
            {
                this.OgretimDonemi_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgretimYili
        {
            get
            {
                return this.OgretimYiliField;
            }
            set
            {
                this.OgretimYiliField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrOgretimYiliDonemiDetay", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrOgretimYiliDonemiDetay : object
    {
        
        private string AkademikAdField;
        
        private string AkademikSoyadField;
        
        private string AkademikUnvanField;
        
        private System.Nullable<int> AkademikUnvan_IDField;
        
        private string BasariDegerlemesiField;
        
        private System.Nullable<int> BasariDegerlemesi_IDField;
        
        private System.Nullable<decimal> BasariNotuField;
        
        private int ButunlemeField;
        
        private string DersAdiField;
        
        private string DersKoduField;
        
        private string DersinDaliField;
        
        private int DersinDali_IDField;
        
        private string DevamKoduField;
        
        private System.Nullable<int> DevamKodu_IDField;
        
        private int FinalField;
        
        private int GecmeNotuField;
        
        private int GrupNoField;
        
        private string HarfNotField;
        
        private int OgrenciDersIDField;
        
        private int S1Field;
        
        private System.Nullable<decimal> SinifOrtalamasiField;
        
        private decimal YilIciOrtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AkademikAd
        {
            get
            {
                return this.AkademikAdField;
            }
            set
            {
                this.AkademikAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AkademikSoyad
        {
            get
            {
                return this.AkademikSoyadField;
            }
            set
            {
                this.AkademikSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AkademikUnvan
        {
            get
            {
                return this.AkademikUnvanField;
            }
            set
            {
                this.AkademikUnvanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AkademikUnvan_ID
        {
            get
            {
                return this.AkademikUnvan_IDField;
            }
            set
            {
                this.AkademikUnvan_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasariDegerlemesi
        {
            get
            {
                return this.BasariDegerlemesiField;
            }
            set
            {
                this.BasariDegerlemesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BasariDegerlemesi_ID
        {
            get
            {
                return this.BasariDegerlemesi_IDField;
            }
            set
            {
                this.BasariDegerlemesi_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BasariNotu
        {
            get
            {
                return this.BasariNotuField;
            }
            set
            {
                this.BasariNotuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Butunleme
        {
            get
            {
                return this.ButunlemeField;
            }
            set
            {
                this.ButunlemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DersAdi
        {
            get
            {
                return this.DersAdiField;
            }
            set
            {
                this.DersAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DersKodu
        {
            get
            {
                return this.DersKoduField;
            }
            set
            {
                this.DersKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DersinDali
        {
            get
            {
                return this.DersinDaliField;
            }
            set
            {
                this.DersinDaliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DersinDali_ID
        {
            get
            {
                return this.DersinDali_IDField;
            }
            set
            {
                this.DersinDali_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevamKodu
        {
            get
            {
                return this.DevamKoduField;
            }
            set
            {
                this.DevamKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevamKodu_ID
        {
            get
            {
                return this.DevamKodu_IDField;
            }
            set
            {
                this.DevamKodu_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Final
        {
            get
            {
                return this.FinalField;
            }
            set
            {
                this.FinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GecmeNotu
        {
            get
            {
                return this.GecmeNotuField;
            }
            set
            {
                this.GecmeNotuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrupNo
        {
            get
            {
                return this.GrupNoField;
            }
            set
            {
                this.GrupNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HarfNot
        {
            get
            {
                return this.HarfNotField;
            }
            set
            {
                this.HarfNotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciDersID
        {
            get
            {
                return this.OgrenciDersIDField;
            }
            set
            {
                this.OgrenciDersIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int S1
        {
            get
            {
                return this.S1Field;
            }
            set
            {
                this.S1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SinifOrtalamasi
        {
            get
            {
                return this.SinifOrtalamasiField;
            }
            set
            {
                this.SinifOrtalamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal YilIciOrt
        {
            get
            {
                return this.YilIciOrtField;
            }
            set
            {
                this.YilIciOrtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrInformation", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class OgrInformation : Wcf_Ogr_ogrservice.Validate
    {
        
        private string AskerlikDurumField;
        
        private System.Nullable<int> AskerlikDurum_IDField;
        
        private string BolumField;
        
        private System.Nullable<int> Bolum_IDField;
        
        private string CinsiyetField;
        
        private int Cinsiyet_IDField;
        
        private string DanismanAdField;
        
        private string DanismanEPostaField;
        
        private string DanismanSoyadField;
        
        private string DanismanUnvanField;
        
        private System.Nullable<int> DanismanUnvan_IDField;
        
        private bool EngelliField;
        
        private System.Nullable<int> EngellilikOraniField;
        
        private string EngellilikTuruField;
        
        private System.Nullable<int> EngellilikTuru_IDField;
        
        private string FakulteField;
        
        private System.Nullable<int> Fakulte_IDField;
        
        private string HazirlikField;
        
        private System.Nullable<int> Hazirlik_IDField;
        
        private System.Nullable<System.DateTime> KayitTarihiField;
        
        private int KayitYiliField;
        
        private string LiseField;
        
        private System.Nullable<int> Lise_IDField;
        
        private System.Nullable<System.DateTime> MezuniyetTarihiField;
        
        private string Nufus_AnaAdiField;
        
        private string Nufus_BabaAdiField;
        
        private string Nufus_CuzdanKayitNoField;
        
        private System.Nullable<System.DateTime> Nufus_DogumTarihiField;
        
        private string Nufus_DogumYeriField;
        
        private System.Nullable<int> Nufus_IDField;
        
        private string Nufus_KanGrubuField;
        
        private System.Nullable<int> Nufus_KanGrubu_IDField;
        
        private string Nufus_KayitliAileSiraNoField;
        
        private string Nufus_KayitliCiltNoField;
        
        private string Nufus_KayitliIlField;
        
        private System.Nullable<int> Nufus_KayitliIl_IDField;
        
        private string Nufus_KayitliIlceField;
        
        private System.Nullable<int> Nufus_KayitliIlce_IDField;
        
        private string Nufus_KayitliMahalleKoyField;
        
        private string Nufus_KayitliSiraNoField;
        
        private string Nufus_MedeniHaliField;
        
        private System.Nullable<int> Nufus_MedeniHali_IDField;
        
        private string Nufus_SeriNoField;
        
        private string OgretimDuzeyiField;
        
        private System.Nullable<int> OgretimDuzeyi_IDField;
        
        private string OgretimTuruField;
        
        private System.Nullable<int> OgretimTuru_IDField;
        
        private string ProgramField;
        
        private string ProgramTuruField;
        
        private int ProgramTuru_IDField;
        
        private System.Nullable<int> Program_IDField;
        
        private string Program_MainField;
        
        private System.Nullable<int> Program_MainIDField;
        
        private int SinifField;
        
        private decimal SureField;
        
        private string UyrukField;
        
        private System.Nullable<int> Uyruk_IDField;
        
        private System.Nullable<int> YoksisBirim_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AskerlikDurum
        {
            get
            {
                return this.AskerlikDurumField;
            }
            set
            {
                this.AskerlikDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AskerlikDurum_ID
        {
            get
            {
                return this.AskerlikDurum_IDField;
            }
            set
            {
                this.AskerlikDurum_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bolum
        {
            get
            {
                return this.BolumField;
            }
            set
            {
                this.BolumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Bolum_ID
        {
            get
            {
                return this.Bolum_IDField;
            }
            set
            {
                this.Bolum_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cinsiyet_ID
        {
            get
            {
                return this.Cinsiyet_IDField;
            }
            set
            {
                this.Cinsiyet_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DanismanAd
        {
            get
            {
                return this.DanismanAdField;
            }
            set
            {
                this.DanismanAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DanismanEPosta
        {
            get
            {
                return this.DanismanEPostaField;
            }
            set
            {
                this.DanismanEPostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DanismanSoyad
        {
            get
            {
                return this.DanismanSoyadField;
            }
            set
            {
                this.DanismanSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DanismanUnvan
        {
            get
            {
                return this.DanismanUnvanField;
            }
            set
            {
                this.DanismanUnvanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DanismanUnvan_ID
        {
            get
            {
                return this.DanismanUnvan_IDField;
            }
            set
            {
                this.DanismanUnvan_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Engelli
        {
            get
            {
                return this.EngelliField;
            }
            set
            {
                this.EngelliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EngellilikOrani
        {
            get
            {
                return this.EngellilikOraniField;
            }
            set
            {
                this.EngellilikOraniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngellilikTuru
        {
            get
            {
                return this.EngellilikTuruField;
            }
            set
            {
                this.EngellilikTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EngellilikTuru_ID
        {
            get
            {
                return this.EngellilikTuru_IDField;
            }
            set
            {
                this.EngellilikTuru_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fakulte
        {
            get
            {
                return this.FakulteField;
            }
            set
            {
                this.FakulteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Fakulte_ID
        {
            get
            {
                return this.Fakulte_IDField;
            }
            set
            {
                this.Fakulte_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hazirlik
        {
            get
            {
                return this.HazirlikField;
            }
            set
            {
                this.HazirlikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Hazirlik_ID
        {
            get
            {
                return this.Hazirlik_IDField;
            }
            set
            {
                this.Hazirlik_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> KayitTarihi
        {
            get
            {
                return this.KayitTarihiField;
            }
            set
            {
                this.KayitTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KayitYili
        {
            get
            {
                return this.KayitYiliField;
            }
            set
            {
                this.KayitYiliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lise
        {
            get
            {
                return this.LiseField;
            }
            set
            {
                this.LiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Lise_ID
        {
            get
            {
                return this.Lise_IDField;
            }
            set
            {
                this.Lise_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MezuniyetTarihi
        {
            get
            {
                return this.MezuniyetTarihiField;
            }
            set
            {
                this.MezuniyetTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_AnaAdi
        {
            get
            {
                return this.Nufus_AnaAdiField;
            }
            set
            {
                this.Nufus_AnaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_BabaAdi
        {
            get
            {
                return this.Nufus_BabaAdiField;
            }
            set
            {
                this.Nufus_BabaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_CuzdanKayitNo
        {
            get
            {
                return this.Nufus_CuzdanKayitNoField;
            }
            set
            {
                this.Nufus_CuzdanKayitNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Nufus_DogumTarihi
        {
            get
            {
                return this.Nufus_DogumTarihiField;
            }
            set
            {
                this.Nufus_DogumTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_DogumYeri
        {
            get
            {
                return this.Nufus_DogumYeriField;
            }
            set
            {
                this.Nufus_DogumYeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nufus_ID
        {
            get
            {
                return this.Nufus_IDField;
            }
            set
            {
                this.Nufus_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KanGrubu
        {
            get
            {
                return this.Nufus_KanGrubuField;
            }
            set
            {
                this.Nufus_KanGrubuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nufus_KanGrubu_ID
        {
            get
            {
                return this.Nufus_KanGrubu_IDField;
            }
            set
            {
                this.Nufus_KanGrubu_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KayitliAileSiraNo
        {
            get
            {
                return this.Nufus_KayitliAileSiraNoField;
            }
            set
            {
                this.Nufus_KayitliAileSiraNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KayitliCiltNo
        {
            get
            {
                return this.Nufus_KayitliCiltNoField;
            }
            set
            {
                this.Nufus_KayitliCiltNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KayitliIl
        {
            get
            {
                return this.Nufus_KayitliIlField;
            }
            set
            {
                this.Nufus_KayitliIlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nufus_KayitliIl_ID
        {
            get
            {
                return this.Nufus_KayitliIl_IDField;
            }
            set
            {
                this.Nufus_KayitliIl_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KayitliIlce
        {
            get
            {
                return this.Nufus_KayitliIlceField;
            }
            set
            {
                this.Nufus_KayitliIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nufus_KayitliIlce_ID
        {
            get
            {
                return this.Nufus_KayitliIlce_IDField;
            }
            set
            {
                this.Nufus_KayitliIlce_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KayitliMahalleKoy
        {
            get
            {
                return this.Nufus_KayitliMahalleKoyField;
            }
            set
            {
                this.Nufus_KayitliMahalleKoyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_KayitliSiraNo
        {
            get
            {
                return this.Nufus_KayitliSiraNoField;
            }
            set
            {
                this.Nufus_KayitliSiraNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_MedeniHali
        {
            get
            {
                return this.Nufus_MedeniHaliField;
            }
            set
            {
                this.Nufus_MedeniHaliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nufus_MedeniHali_ID
        {
            get
            {
                return this.Nufus_MedeniHali_IDField;
            }
            set
            {
                this.Nufus_MedeniHali_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nufus_SeriNo
        {
            get
            {
                return this.Nufus_SeriNoField;
            }
            set
            {
                this.Nufus_SeriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgretimDuzeyi
        {
            get
            {
                return this.OgretimDuzeyiField;
            }
            set
            {
                this.OgretimDuzeyiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OgretimDuzeyi_ID
        {
            get
            {
                return this.OgretimDuzeyi_IDField;
            }
            set
            {
                this.OgretimDuzeyi_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgretimTuru
        {
            get
            {
                return this.OgretimTuruField;
            }
            set
            {
                this.OgretimTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OgretimTuru_ID
        {
            get
            {
                return this.OgretimTuru_IDField;
            }
            set
            {
                this.OgretimTuru_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Program
        {
            get
            {
                return this.ProgramField;
            }
            set
            {
                this.ProgramField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramTuru
        {
            get
            {
                return this.ProgramTuruField;
            }
            set
            {
                this.ProgramTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgramTuru_ID
        {
            get
            {
                return this.ProgramTuru_IDField;
            }
            set
            {
                this.ProgramTuru_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Program_ID
        {
            get
            {
                return this.Program_IDField;
            }
            set
            {
                this.Program_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Program_Main
        {
            get
            {
                return this.Program_MainField;
            }
            set
            {
                this.Program_MainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Program_MainID
        {
            get
            {
                return this.Program_MainIDField;
            }
            set
            {
                this.Program_MainIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sinif
        {
            get
            {
                return this.SinifField;
            }
            set
            {
                this.SinifField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sure
        {
            get
            {
                return this.SureField;
            }
            set
            {
                this.SureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Uyruk_ID
        {
            get
            {
                return this.Uyruk_IDField;
            }
            set
            {
                this.Uyruk_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YoksisBirim_ID
        {
            get
            {
                return this.YoksisBirim_IDField;
            }
            set
            {
                this.YoksisBirim_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Validate", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf_Ogr_ogrservice.OgrInformation))]
    public partial class Validate : object
    {
        
        private string AdField;
        
        private System.Nullable<int> CiftYanDal_IDField;
        
        private string DurumField;
        
        private int Durum_IDField;
        
        private int OgrenciIDField;
        
        private string OgrenciNoField;
        
        private string SoyadField;
        
        private string TcKimlikNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiftYanDal_ID
        {
            get
            {
                return this.CiftYanDal_IDField;
            }
            set
            {
                this.CiftYanDal_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Durum_ID
        {
            get
            {
                return this.Durum_IDField;
            }
            set
            {
                this.Durum_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgrenciID
        {
            get
            {
                return this.OgrenciIDField;
            }
            set
            {
                this.OgrenciIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenciNo
        {
            get
            {
                return this.OgrenciNoField;
            }
            set
            {
                this.OgrenciNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikNo
        {
            get
            {
                return this.TcKimlikNoField;
            }
            set
            {
                this.TcKimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyrukInformation", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class UyrukInformation : object
    {
        
        private string AdiField;
        
        private string KitaAdiField;
        
        private System.Nullable<int> KitaAdi_IDField;
        
        private int UyrukIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi
        {
            get
            {
                return this.AdiField;
            }
            set
            {
                this.AdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KitaAdi
        {
            get
            {
                return this.KitaAdiField;
            }
            set
            {
                this.KitaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KitaAdi_ID
        {
            get
            {
                return this.KitaAdi_IDField;
            }
            set
            {
                this.KitaAdi_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyrukID
        {
            get
            {
                return this.UyrukIDField;
            }
            set
            {
                this.UyrukIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SehirIlceInformation", Namespace="http://schemas.datacontract.org/2004/07/BayWcf.Student.App_Data.Response")]
    public partial class SehirIlceInformation : object
    {
        
        private string AdiField;
        
        private int IlIlceIDField;
        
        private int KodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi
        {
            get
            {
                return this.AdiField;
            }
            set
            {
                this.AdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlIlceID
        {
            get
            {
                return this.IlIlceIDField;
            }
            set
            {
                this.IlIlceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kod
        {
            get
            {
                return this.KodField;
            }
            set
            {
                this.KodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf_Ogr_ogrservice.IOgrService")]
    public interface IOgrService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrImage", ReplyAction="http://tempuri.org/IOgrService/GetByOgrImageResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrImage_Response> GetByOgrImageAsync(string username, string password, string value, bool isogrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrContact", ReplyAction="http://tempuri.org/IOgrService/GetByOgrContactResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrContact_Response> GetByOgrContactAsync(string username, string password, string value, bool isogrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrContactUnipaMasterDB", ReplyAction="http://tempuri.org/IOgrService/GetByOgrContactUnipaMasterDBResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrContactUnipaMasterDB_Response> GetByOgrContactUnipaMasterDBAsync(string username, string password, string ogrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrAddress", ReplyAction="http://tempuri.org/IOgrService/GetByOgrAddressResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrAddress_Response> GetByOgrAddressAsync(string username, string password, string value, bool isogrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrCiftYanDal", ReplyAction="http://tempuri.org/IOgrService/GetByOgrCiftYanDalResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrCiftYandal_Response> GetByOgrCiftYanDalAsync(string username, string password, int ciftyandalid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrMktr", ReplyAction="http://tempuri.org/IOgrService/GetByOgrMktrResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrMktr_Response> GetByOgrMktrAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgretimYiliDonemi", ReplyAction="http://tempuri.org/IOgrService/GetByOgretimYiliDonemiResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrOgretimYiliDonemi_Response> GetByOgretimYiliDonemiAsync(string username, string password, string ogrencino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgretimYiliDonemiDetay", ReplyAction="http://tempuri.org/IOgrService/GetByOgretimYiliDonemiDetayResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrOgretimYiliDonemiDetay_Response> GetByOgretimYiliDonemiDetayAsync(string username, string password, string ogrencino, int ogretimyili, int ogretimdonemiid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrNo", ReplyAction="http://tempuri.org/IOgrService/GetByOgrNoResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrInformationOgrNo_Response> GetByOgrNoAsync(string username, string password, string ogrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByTckn", ReplyAction="http://tempuri.org/IOgrService/GetByTcknResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrInformation_Response> GetByTcknAsync(string username, string password, string tckn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetByOgrDataList", ReplyAction="http://tempuri.org/IOgrService/GetByOgrDataListResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrInformation_Response> GetByOgrDataListAsync(string username, string password, bool istckn, string values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetUyrukList", ReplyAction="http://tempuri.org/IOgrService/GetUyrukListResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.UyrukInformation_Response> GetUyrukListAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetSehirList", ReplyAction="http://tempuri.org/IOgrService/GetSehirListResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.SehirIlceInformation_Response> GetSehirListAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/GetIlceList", ReplyAction="http://tempuri.org/IOgrService/GetIlceListResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.SehirIlceInformation_Response> GetIlceListAsync(string username, string password, int ilkodu, bool isplaka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/ValidateOgrNo", ReplyAction="http://tempuri.org/IOgrService/ValidateOgrNoResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.ValidateOgrNo_Response> ValidateOgrNoAsync(string username, string password, string ogrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrService/ValidateTckn", ReplyAction="http://tempuri.org/IOgrService/ValidateTcknResponse")]
        System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.ValidateTckn_Response> ValidateTcknAsync(string username, string password, string tckn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IOgrServiceChannel : Wcf_Ogr_ogrservice.IOgrService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class OgrServiceClient : System.ServiceModel.ClientBase<Wcf_Ogr_ogrservice.IOgrService>, Wcf_Ogr_ogrservice.IOgrService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OgrServiceClient() : 
                base(OgrServiceClient.GetDefaultBinding(), OgrServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IOgrService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OgrServiceClient.GetBindingForEndpoint(endpointConfiguration), OgrServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OgrServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OgrServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrImage_Response> GetByOgrImageAsync(string username, string password, string value, bool isogrno)
        {
            return base.Channel.GetByOgrImageAsync(username, password, value, isogrno);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrContact_Response> GetByOgrContactAsync(string username, string password, string value, bool isogrno)
        {
            return base.Channel.GetByOgrContactAsync(username, password, value, isogrno);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrContactUnipaMasterDB_Response> GetByOgrContactUnipaMasterDBAsync(string username, string password, string ogrno)
        {
            return base.Channel.GetByOgrContactUnipaMasterDBAsync(username, password, ogrno);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrAddress_Response> GetByOgrAddressAsync(string username, string password, string value, bool isogrno)
        {
            return base.Channel.GetByOgrAddressAsync(username, password, value, isogrno);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrCiftYandal_Response> GetByOgrCiftYanDalAsync(string username, string password, int ciftyandalid)
        {
            return base.Channel.GetByOgrCiftYanDalAsync(username, password, ciftyandalid);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrMktr_Response> GetByOgrMktrAsync(string username, string password)
        {
            return base.Channel.GetByOgrMktrAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrOgretimYiliDonemi_Response> GetByOgretimYiliDonemiAsync(string username, string password, string ogrencino)
        {
            return base.Channel.GetByOgretimYiliDonemiAsync(username, password, ogrencino);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrOgretimYiliDonemiDetay_Response> GetByOgretimYiliDonemiDetayAsync(string username, string password, string ogrencino, int ogretimyili, int ogretimdonemiid)
        {
            return base.Channel.GetByOgretimYiliDonemiDetayAsync(username, password, ogrencino, ogretimyili, ogretimdonemiid);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrInformationOgrNo_Response> GetByOgrNoAsync(string username, string password, string ogrno)
        {
            return base.Channel.GetByOgrNoAsync(username, password, ogrno);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrInformation_Response> GetByTcknAsync(string username, string password, string tckn)
        {
            return base.Channel.GetByTcknAsync(username, password, tckn);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.OgrInformation_Response> GetByOgrDataListAsync(string username, string password, bool istckn, string values)
        {
            return base.Channel.GetByOgrDataListAsync(username, password, istckn, values);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.UyrukInformation_Response> GetUyrukListAsync(string username, string password)
        {
            return base.Channel.GetUyrukListAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.SehirIlceInformation_Response> GetSehirListAsync(string username, string password)
        {
            return base.Channel.GetSehirListAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.SehirIlceInformation_Response> GetIlceListAsync(string username, string password, int ilkodu, bool isplaka)
        {
            return base.Channel.GetIlceListAsync(username, password, ilkodu, isplaka);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.ValidateOgrNo_Response> ValidateOgrNoAsync(string username, string password, string ogrno)
        {
            return base.Channel.ValidateOgrNoAsync(username, password, ogrno);
        }
        
        public System.Threading.Tasks.Task<Wcf_Ogr_ogrservice.ValidateTckn_Response> ValidateTcknAsync(string username, string password, string tckn)
        {
            return base.Channel.ValidateTcknAsync(username, password, tckn);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IOgrService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IOgrService))
            {
                return new System.ServiceModel.EndpointAddress("https://ogrencisorgula.bayburt.edu.tr/OgrService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OgrServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IOgrService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OgrServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IOgrService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IOgrService,
        }
    }
}
