//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf_Yoksis_DocentlikBilgi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/docentlik/2021/06", ConfigurationName="Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiPort")]
    public interface DocentlikBilgiPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiResponse1> DocentlikBilgiAsync(Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/docentlik/2021/06")]
    public partial class DocentlikBilgiRequestType
    {
        
        private IstekBilgiTip istekField;
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IstekBilgiTip Istek
        {
            get
            {
                return this.istekField;
            }
            set
            {
                this.istekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/docentlik/2021/06")]
    public partial class IstekBilgiTip
    {
        
        private string istekTarihiField;
        
        private string istekIdField;
        
        private string kullaniciAdiField;
        
        private string uygulamaAdiField;
        
        private string uygulamaSunucuAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string IstekTarihi
        {
            get
            {
                return this.istekTarihiField;
            }
            set
            {
                this.istekTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IstekId
        {
            get
            {
                return this.istekIdField;
            }
            set
            {
                this.istekIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string KullaniciAdi
        {
            get
            {
                return this.kullaniciAdiField;
            }
            set
            {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
        public string UygulamaAdi
        {
            get
            {
                return this.uygulamaAdiField;
            }
            set
            {
                this.uygulamaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4)]
        public string UygulamaSunucuAdi
        {
            get
            {
                return this.uygulamaSunucuAdiField;
            }
            set
            {
                this.uygulamaSunucuAdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/docentlik/2021/06")]
    public partial class SonucBilgiTip
    {
        
        private int sonucKodField;
        
        private string disSistemSonucKodField;
        
        private string sonucMesajField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SonucKod
        {
            get
            {
                return this.sonucKodField;
            }
            set
            {
                this.sonucKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string DisSistemSonucKod
        {
            get
            {
                return this.disSistemSonucKodField;
            }
            set
            {
                this.disSistemSonucKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SonucMesaj
        {
            get
            {
                return this.sonucMesajField;
            }
            set
            {
                this.sonucMesajField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/docentlik/2021/06")]
    public partial class DocentlikBilgi
    {
        
        private long tcKimlikNoField;
        
        private string bilimAlaniField;
        
        private string unvanTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BilimAlani
        {
            get
            {
                return this.bilimAlaniField;
            }
            set
            {
                this.bilimAlaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UnvanTarihi
        {
            get
            {
                return this.unvanTarihiField;
            }
            set
            {
                this.unvanTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/docentlik/2021/06")]
    public partial class DocentlikBilgiResponse
    {
        
        private DocentlikBilgi[] docentlikBilgiField;
        
        private SonucBilgiTip sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocentlikBilgi", Order=0)]
        public DocentlikBilgi[] DocentlikBilgi
        {
            get
            {
                return this.docentlikBilgiField;
            }
            set
            {
                this.docentlikBilgiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SonucBilgiTip Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocentlikBilgiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocentlikBilgiRequest", Namespace="http://www.yok.gov.tr/docentlik/2021/06", Order=0)]
        public Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequestType DocentlikBilgiRequest1;
        
        public DocentlikBilgiRequest()
        {
        }
        
        public DocentlikBilgiRequest(Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequestType DocentlikBilgiRequest1)
        {
            this.DocentlikBilgiRequest1 = DocentlikBilgiRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocentlikBilgiResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/docentlik/2021/06", Order=0)]
        public Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiResponse DocentlikBilgiResponse;
        
        public DocentlikBilgiResponse1()
        {
        }
        
        public DocentlikBilgiResponse1(Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiResponse DocentlikBilgiResponse)
        {
            this.DocentlikBilgiResponse = DocentlikBilgiResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface DocentlikBilgiPortChannel : Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DocentlikBilgiPortClient : System.ServiceModel.ClientBase<Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiPort>, Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocentlikBilgiPortClient() : 
                base(DocentlikBilgiPortClient.GetDefaultBinding(), DocentlikBilgiPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DocentlikBilgiPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocentlikBilgiPortClient(EndpointConfiguration endpointConfiguration) : 
                base(DocentlikBilgiPortClient.GetBindingForEndpoint(endpointConfiguration), DocentlikBilgiPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocentlikBilgiPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocentlikBilgiPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocentlikBilgiPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocentlikBilgiPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocentlikBilgiPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiResponse1> Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiPort.DocentlikBilgiAsync(Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequest request)
        {
            return base.Channel.DocentlikBilgiAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiResponse1> DocentlikBilgiAsync(Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequestType DocentlikBilgiRequest1)
        {
            Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequest inValue = new Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiRequest();
            inValue.DocentlikBilgiRequest1 = DocentlikBilgiRequest1;
            return ((Wcf_Yoksis_DocentlikBilgi.DocentlikBilgiPort)(this)).DocentlikBilgiAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocentlikBilgiPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocentlikBilgiPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://servisler.yok.gov.tr/ws/DocentlikBilgi");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocentlikBilgiPortClient.GetBindingForEndpoint(EndpointConfiguration.DocentlikBilgiPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocentlikBilgiPortClient.GetEndpointAddress(EndpointConfiguration.DocentlikBilgiPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            DocentlikBilgiPortSoap11,
        }
    }
}
